const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require(process.env.HOURLINK_PLAYWRIGHT || require("node:path").join(require("node:os").homedir(), ".cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright"));
(async () => {
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Hong_Kong'});
 const origin='http://127.0.0.1:8000';
 fs.mkdirSync('artifacts/browser',{recursive:true});
 await context.request.post(origin+'/api/v1/auth/demo-login',{data:{username:'reviewer',case:'cash'}});
 await context.request.post(origin+'/api/v1/demo/reset',{data:{case:'cash'},headers:{'Idempotency-Key':require('node:crypto').randomUUID()}});
 await context.request.post(origin+'/api/v1/auth/demo-login',{data:{username:'zao',case:'cash'}});
 const external=[]; await context.route('**/*',route=>{const u=new URL(route.request().url()); if(!['127.0.0.1','localhost'].includes(u.hostname)){external.push(u.href);return route.abort();}return route.continue();});
 const page=await context.newPage(); const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8000');
 await page.getByRole('heading',{name:/你的能力/}).waitFor();
 await page.screenshot({path:'artifacts/browser/market-desktop.png',fullPage:true});
 await page.getByRole('link',{name:/整理一份散亂/}).click();
 await page.getByRole('heading',{name:'誰適合這次需求？'}).waitFor();
 await page.getByRole('button',{name:'查看評估依據'}).first().click();
 await page.getByRole('dialog').waitFor();
 await page.getByRole('button',{name:'關閉',exact:true}).click();
 await page.getByRole('button',{name:'選擇並生成方案'}).first().click();
 await page.getByRole('button',{name:'建立雙方協議'}).waitFor();
 await page.screenshot({path:'artifacts/browser/proposal.png',fullPage:true});
 await page.getByRole('button',{name:'建立雙方協議'}).click();
 await page.getByRole('button',{name:'我確認此版本協議'}).click();
 await page.getByRole('button',{name:'切換演示身份'}).click();
 await page.locator('.account-menu').getByRole('button',{name:'知 林知行'}).click();
 await page.getByRole('button',{name:'我確認此版本協議'}).click();
 await page.getByRole('button',{name:'切換演示身份'}).click();
 await page.locator('.account-menu').getByRole('button',{name:'予 周予安'}).click();
 await page.getByRole('button',{name:'模擬預留'}).click();
 await page.getByRole('button',{name:'切換演示身份'}).click();
 await page.locator('.account-menu').getByRole('button',{name:'知 林知行'}).click();
 await page.getByRole('button',{name:'提交交付',exact:true}).click();
 await page.getByRole('dialog').getByRole('textbox').fill('依照驗收樣本交付已整理的工作表與修改說明');
 await page.getByRole('dialog').getByRole('button',{name:'提交',exact:true}).click();
 await page.getByRole('button',{name:'切換演示身份'}).click();
 await page.locator('.account-menu').getByRole('button',{name:'予 周予安'}).click();
 await page.getByRole('button',{name:'驗收並確認時間'}).click();
 await page.getByRole('dialog').getByRole('button',{name:'提交',exact:true}).click();
 await page.locator('.stage-card').first().getByText('本輪服務已完成').waitFor();
 await page.reload();
 await page.locator('.stage-card').first().getByText('本輪服務已完成').waitFor();
 await page.screenshot({path:'artifacts/browser/order.png',fullPage:true});
 await page.getByRole('link',{name:'能力與時間',exact:true}).click();
 await page.getByRole('heading',{name:'周予安'}).waitFor();
 assert.deepEqual(external,[], 'core flow contacted external service');
 const mobile=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Hong_Kong'});const phone=await mobile.newPage();
 await phone.goto('http://127.0.0.1:8000');await phone.getByRole('heading',{name:/你的能力/}).waitFor();
 await phone.screenshot({path:'artifacts/browser/market-mobile.png',fullPage:true});
 assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile overflow');
 assert.deepEqual(errors,[]);
 fs.writeFileSync('artifacts/browser/result.json',JSON.stringify({passed:true,errors,desktop:'1440x1000',mobile:'390x844',checks:['market','evidence detail','proposal','both signatures','reserve','submit','accept','refresh recovery','core flow without external services','mobile overflow']},null,2));
 await browser.close();console.log('Browser checks passed');
})().catch(e=>{console.error(e);process.exit(1)});
